# Generated by Django 5.2.4 on 2025-07-29 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_alter_fotografia_data_fotografia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
